name: run-tests

on: [push]

jobs:
    test:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Setup PHP
          uses: shivammathur/setup-php@master
          with:
            php-version: 8.2

        - name: Install dependencies
          run: composer install -n --prefer-dist --no-interaction --no-suggest --no-progress --optimize-autoloader

        - name: Execute tests
          run: vendor/bin/phpunit
