name: run-tests

on: [push]

jobs:
    test:
      runs-on: ubuntu-latest
      strategy:
        matrix:
          php-version: ['8.3', '8.4', '8.5']
      steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Setup PHP
          uses: shivammathur/setup-php@master
          with:
            php-version: ${{ matrix.php-version }}

        - name: Install dependencies
          run: composer install -n --prefer-dist --no-interaction --no-suggest --no-progress --optimize-autoloader

        - name: Execute tests
          run: vendor/bin/phpunit
